# Generated by Django 3.2.7 on 2021-09-26 18:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('main_photo', models.ImageField(upload_to='listing/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='listing/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='listing/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='listing/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='listing/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='listing/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='listing/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(default=datetime.datetime.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
